Dcat tool as background process
statisticssweden/PxWeb pull request #443
Opened 2023-05-16 07:13 UTC by jerikso

* Dcat tool can now be run as a background process by the BackgroundWorker
* Dcat settings are stored separately for each database in the corresponding database.config file
* The current status of creating the Dcat file is now shown on the interface

2023-05-23 05:56 UTC, likp reviewed
You should disable the generate button if the database is in a state where it is waiting or generating the DCAT file.

2023-05-23 14:38 UTC, likp approved these changes

2023-05-24 07:10 UTC, MikaelNordberg requested changes
You should make a note in the CHANGES.txt file of your changes. Otherwise it looks good.

2023-05-30 06:33 UTC, MikaelNordberg approved these changes
Looks good

2023-05-30 07:34 UTC, merged