Added filetype csv2 and csv3 to PCAxis.Web.Controls
statisticssweden/PxWeb pull request #495
Opened 2023-09-20 08:50 UTC by masv-scb

2023-09-20 09:17 UTC, MikaelNordberg requested changes
Looks good except for the comments

2023-09-20 09:17 UTC, MikaelNordberg commented on PCAxis.Web.Controls/FileTypes/Csv/Csv2FileType.vb
> +    ''' Creates a html file and sends it to the user
Should be csv in the comment

2023-09-20 09:17 UTC, MikaelNordberg commented on PCAxis.Web.Controls/FileTypes/Csv/Csv3FileType.vb
> +    ''' Creates a html file and sends it to the user
Should be csv in the comment

2023-09-20 09:24 UTC, MikaelNordberg approved these changes
Looks good

2023-09-20 11:36 UTC, likp reviewed
@MikaelNordberg should we also be able to override saved queries with csv2 and csv3?

2023-09-25 08:49 UTC, MikaelNordberg approved these changes
Looks good

2023-09-25 08:54 UTC, MikaelNordberg approved these changes
Looks good

2023-09-25 11:32 UTC, likp approved these changes

2023-09-25 11:33 UTC, merged